name: Wget-all-rakersfu

on:
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip tar

      - name: Download and prepare files
        run: |
          mkdir -p build && cd build

          # 下载并解压 Xray-core
          wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip Xray-linux-64.zip
          rm -f Xray-linux-64.zip
          mv xray xy

          # 下载 ttyd
          wget -O td https://github.com/tsl0922/ttyd/releases/latest/download/ttyd.x86_64
          chmod +x td

          # 下载 supercronic
          wget -O supercronic https://github.com/aptible/supercronic/releases/latest/download/supercronic-linux-amd64
          chmod +x supercronic

      - name: Package release files
        run: |
          tar -czf release-package.tar.gz build/

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release-package.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
